# Generated by Django 6.0 on 2025-12-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('cpf', models.CharField(max_length=14)),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('TRIAGEM', 'Em Triagem'), ('ATENDIMENTO', 'Em Atendimento')], default='AGUARDANDO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
