# Generated by Django 6.0 on 2025-12-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='status',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
