# Generated by Django 6.0 on 2025-12-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('TRIAGEM', 'Em Triagem'), ('ATENDIMENTO', 'Em Atendimento')], default='AGUARDANDO', max_length=20),
        ),
    ]
