# Generated by Django 6.0 on 2025-12-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
