# Generated by Django 6.0 on 2025-12-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='trocar_senha',
            field=models.BooleanField(default=True),
        ),
    ]
