# Generated by Django 6.0 on 2025-12-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
