# Generated by Django 6.0 on 2025-12-23 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_alter_consulta_data'),
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='criado_em',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medico.medico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_TRIAGEM', 'Aguardando Triagem'), ('AGUARDANDO_MEDICO', 'Aguardando Médico'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('FINALIZADA', 'Finalizada')], default='AGUARDANDO_TRIAGEM', max_length=30),
        ),
    ]
