# Generated by Django 6.0 on 2025-12-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_triagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Triagem',
        ),
    ]
