# Generated by Django 6.0 on 2025-12-23 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_remove_consulta_criado_em_alter_consulta_medico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='paciente',
        ),
    ]
