# Generated by Django 6.0 on 2025-12-23 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0004_remove_consulta_paciente'),
        ('medico', '0001_initial'),
        ('pacientes', '0002_remove_paciente_criado_em_remove_paciente_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medico.medico'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(default='AGUARDANDO_TRIAGEM', max_length=30),
        ),
    ]
