# Generated by Django 6.0 on 2025-12-23 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0006_prescricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescricao',
            name='data',
        ),
        migrations.AlterField(
            model_name='prescricao',
            name='consulta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consulta.consulta'),
        ),
    ]
