# Generated by Django 6.0 on 2025-12-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0007_remove_prescricao_data_alter_prescricao_consulta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescricao',
            old_name='descricao',
            new_name='orientacoes',
        ),
        migrations.AddField(
            model_name='prescricao',
            name='dosagem',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescricao',
            name='medicamento',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
