# Generated by Django 6.0 on 2025-12-23 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0008_rename_descricao_prescricao_orientacoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescricao',
            name='consulta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescricao', to='consulta.consulta'),
        ),
    ]
