# Generated by Django 6.0 on 2025-12-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0009_alter_prescricao_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescricao',
            name='dosagem',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prescricao',
            name='medicamento',
            field=models.CharField(max_length=255),
        ),
    ]
