# Generated by Django 6.0 on 2025-12-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0010_alter_prescricao_dosagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescricao',
            name='dosagem',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prescricao',
            name='medicamento',
            field=models.CharField(max_length=100),
        ),
    ]
