# Generated by Django 6.0 on 2025-12-22 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consulta', '0001_initial'),
        ('enfermeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressao', models.CharField(max_length=10)),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consulta.consulta')),
                ('enfermeiro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enfermeiro.enfermeiro')),
            ],
        ),
    ]
