# Generated by Django 6.0 on 2025-12-23 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consulta', '0001_initial'),
        ('enfermeiro', '0001_initial'),
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pressao', models.CharField(max_length=10)),
                ('sintomas', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consulta.consulta')),
                ('enfermeiro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enfermeiro.enfermeiro')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medico.medico')),
            ],
        ),
    ]
