# Generated by Django 6.0 on 2025-12-23 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
        ('enfermeiro', '0001_initial'),
        ('triagem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triagem',
            old_name='data',
            new_name='criado_em',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='sintomas',
        ),
        migrations.AddField(
            model_name='triagem',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='consulta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triagem', to='consulta.consulta'),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='enfermeiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enfermeiro.enfermeiro'),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='pressao',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
