# Generated by Django 6.0 on 2025-12-23 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0005_consulta_paciente_alter_consulta_medico_and_more'),
        ('enfermeiro', '0001_initial'),
        ('triagem', '0002_rename_data_triagem_criado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagem',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='medico',
        ),
        migrations.AlterField(
            model_name='triagem',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='triagem',
            name='consulta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consulta.consulta'),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='enfermeiro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enfermeiro.enfermeiro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='triagem',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='triagem',
            name='pressao',
            field=models.CharField(max_length=20),
        ),
    ]
