# Generated by Django 6.0 on 2025-12-23 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0003_remove_triagem_criado_em_remove_triagem_medico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagem',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='enfermeiro',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='pressao',
        ),
    ]
