# Generated by Django 6.0 on 2025-12-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0004_remove_triagem_altura_remove_triagem_enfermeiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagem',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triagem',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triagem',
            name='pressao',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
