# Generated by Django 6.0 on 2025-12-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0005_triagem_altura_triagem_peso_triagem_pressao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='altura',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='peso',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='pressao',
            field=models.CharField(max_length=10),
        ),
    ]
